name: AutoDoc
version: 2016.01.31
date: 31/01/2016
description: Generate documentation from GAP source code

authors:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Max Horn
      url: http://www.quendi.de/math

maintainers:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Max Horn
      url: http://www.quendi.de/math

GAP: ">= 4.5"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/AutoDoc
readme: https://gap-packages.github.io/AutoDoc/README
packageinfo: https://gap-packages.github.io/AutoDoc/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/AutoDoc/releases/download/v2016.01.31/AutoDoc-2016.01.31.tar.gz

abstract: 

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
